### ISSUE TITLE
请问能否增加文档和例子呢？

### ISSUE THREAD

**Issue by maxvint** [flexih/CorePlayer.Swift#1]
你好，最近我们在一个在线教育项目中使用你这个播放器，目前总体有2个问题：
1.文档太(mei)少(you)，对源码现在正在理解中...
2.给你demo能否增加如进度条、预加载、快进/快退这些功能呢？
我现在基于这个也实现了快进、快退、进度条的功能，不知道下来会持续维护这个项目吗？

**Comment by flexih** [comment]
1.接下来会在逐步添加注释 :)
2.进度条相关的是
optional func durationAvailable(duration: NSTimeInterval) //获得到播放时长
optional func played(duration: NSTimeInterval) //播放进度
optional func playable(duration: NSTimeInterval) //缓冲进度
预加载是自动进行的，快进可以通过CorePlayerFeature获得AVPlayer，直接操作AVPlayer即可
3.会持续维护
4.如果可以请提供你的项目的网址和logo地址，我弄个使用者列表 :)

**Comment by maxvint** [comment]
好的，看到这个我就放心了，项目到1月份才上线，到时候发布了，我给你网址。现在基本的功能也都实现了，话说这个代码写的真赞，赞，赞......

**Comment by flexih** [comment]
好的
