### ISSUE TITLE
Get some error

### ISSUE THREAD

**Issue by chaocharleswang** [flexih/CorePlayer.Swift#10]
`let VideoURL = "http://xxx.mp4"

class ViewController: NSViewController, CPModuleDelegate
{
    @IBOutlet weak var vPlayer: NSView!
    @IBOutlet weak var tfDuration: NSTextField!
    
    // Player
    let player = CorePlayer()
    
    var moduleID: Int = 0
    var moduleManager: CPModuleManager?
    var moduleDelegate: CorePlayerFeature?
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        
        self.vPlayer.wantsLayer = true
        self.vPlayer.layer?.backgroundColor = CGColor.black
        
        // Initialize player view
        player.moduleManager().initModules([ViewController.self])
        player.view().translatesAutoresizingMaskIntoConstraints = false
        vPlayer.addSubview(player.view())
        
        NSLayoutConstraint.init(item: player.view(), attribute: .leading, relatedBy: .equal, toItem: vPlayer, attribute: .leading, multiplier: 1, constant: 0).isActive = true
        NSLayoutConstraint.init(item: player.view(), attribute: .trailing, relatedBy: .equal, toItem: vPlayer, attribute: .trailing, multiplier: 1, constant: 0).isActive = true
        NSLayoutConstraint.init(item: player.view(), attribute: .top, relatedBy: .equal, toItem: vPlayer, attribute: .top, multiplier: 1, constant: 0).isActive = true
        NSLayoutConstraint.init(item: player.view(), attribute: .bottom, relatedBy: .equal, toItem: vPlayer, attribute: .bottom, multiplier: 1, constant: 0).isActive = true
    }
    
    override func viewDidAppear()
    {
        super.viewDidAppear()
        
        self.player.playURL(URL(string: VideoURL))
    }
    
    func initModule() { }
    
    func deinitModule() { }
    
    func moduleType() -> ModuleType
    {
        return .feature
    }
    
    func durationAvailable(_ duration: TimeInterval)
    {
        self.tfDuration.stringValue = "\(duration)"
    }
}`

In function durationAvailable(), I got a nil error for the text field "tfDuration". Is there something wrong with the code? Thanks a lot!

**Comment by flexih** [comment]
please run OSXDemo first

**Comment by chaocharleswang** [comment]
I have tried the OSXDemo for swift 4. It uses a separate class EventModule. Can I use CPModuleDelegate in the NSViewController class? I want to control play button and time slider in the delegate functions within the same class. thanks

**Comment by chaocharleswang** [comment]
For example, it is convenient to update the time slider (declared in NSViewController)  in played() function within the same class (NSViewController).

**Comment by flexih** [comment]
separate features  is the purpose of the project.
