### ISSUE TITLE
Do you have plans to update to swift 4?

### ISSUE THREAD

**Issue by FrontierApp** [flexih/CorePlayer.Swift#6]

**Comment by flexih** [comment]
Yes, but I can't tell the exact time. Do you use CorePlayer in your project?

**Comment by FrontierApp** [comment]
Yes. I want to use it. It is very useful for my macOS app.

On Sep 25, 2017, at 22:26, Xinghua Fan <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes, but I can't tell the exact time. Do you use CorePlayer in your project?

**Comment by flexih** [comment]
Done, check out branch Swift4.

**Comment by FrontierApp** [comment]
Thanks a lot!

On Sep 26, 2017, at 00:36, Xinghua Fan <notifications@github.com<mailto:notifications@github.com>> wrote:


Done, check out branch Swift4.
