### ISSUE TITLE
How can I divide playURL() into two steps?

### ISSUE THREAD

**Issue by chaocharleswang** [flexih/CorePlayer.Swift#7]
When I integrate your code into my app. I have the following problem:

playURL() ->

1. setURL()
    Initialize the video before play (e.g., buffer video)
2. play()
    Immediately play the video

Thanks!

**Comment by flexih** [comment]
cp.dpause()
cp.playURL()

**Comment by chaocharleswang** [comment]
Thanks Xinhua for your reply!

According to my understanding,

firstly, cp.dpause() and cp.playURL()
secondly, cp.play() when I wanna immediately play the video

correct? thx

**Comment by flexih** [comment]
yes
