### ISSUE TITLE
About playable()

### ISSUE THREAD

**Issue by chaocharleswang** [flexih/CorePlayer.Swift#9]
CorePlayer is a very useful program for my app.

I have a requirement for this player. I am not sure if I can do it with CorePlayer as follows:

Step 1. Set a streaming video (long-time video, e.g., 3600s -> 1hr) URL to the player via playURL();
Step 2. Seek to some time point via seekTo(), e.g., starting from 500s, pause video at this time point;
Step 3. Monitor playable() until it buffers to some time point, e.g., 510s (buffering 10s from 500s to 510s);
Step 4. Immediately play the video via play().

My question:
1. Can CorePlayer work as aboves?
2. Can the video be immediately played at Step 4?
3. How can I know when the player pauses to play video because of no buffering?

Thanks a lot!

**Comment by flexih** [comment]
1.
Step1, Step2, can be done together, use cp. playURLs([CPURL])
Step 3 looks like to work, you have to try it
2.sure if buffered
3. pend for buffering
optional func willPend()

**Comment by chaocharleswang** [comment]
Cool! Thanks for your quick reply. I will try them.
